// <auto-generated />
using CustomerLocationRP.Services.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CustomerLocationRP.Services.Migrations
{
    [DbContext(typeof(CustomerDbContext))]
    [Migration("20230417185309_MigrationV2")]
    partial class MigrationV2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CustomerLocationRP.Services.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerId")
                        .HasName("PrimaryKey_CustomerId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("CustomerLocationRP.Services.Models.Spouse", b =>
                {
                    b.Property<int>("SpouseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SpouseId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SpouseId");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("Spouse");
                });

            modelBuilder.Entity("CustomerLocationRP.Services.Models.Spouse", b =>
                {
                    b.HasOne("CustomerLocationRP.Services.Models.Customer", "Customer")
                        .WithOne("Spouse")
                        .HasForeignKey("CustomerLocationRP.Services.Models.Spouse", "CustomerId");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CustomerLocationRP.Services.Models.Customer", b =>
                {
                    b.Navigation("Spouse");
                });
#pragma warning restore 612, 618
        }
    }
}
